---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: dictator.wellcloud.welljoint.com
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lKQU8xM2hZZnh2K1NDTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014SVRBZkJnTlYKQkFNTUdHUnBZM1JoZEc5eUxtdDFZbVV0YzNsemRHVnRMbk4yWXpBZ0Z3MHlNekE1TURVd05qTXpOVEJhR0E4eQpNRFV4TURFeU1UQTJNek0xTUZvd0l6RWhNQjhHQTFVRUF3d1laR2xqZEdGMGIzSXVhM1ZpWlMxemVYTjBaVzB1CmMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVZc2tVbnRnTDJXaFdmTkEKOXBCY1NRVHJwMU9EL0dTRXVKWmRpdFdTelNuKyt6TmJCa3JhT3pUblR2Tk9RNGkrSmQ0eFpHeHpEeWg1M1FrNAp4UEFNQUxwSnVSa1h1M0x0cmRNT2QrRjVMNDRlMkMxVnZUR043dnl4QUV6ZTk4YUN0NzBrOWdKZXpGM1BZTWwzCklSb1BiaVVqekQxcDc4UlRYZ2FibkRNTzgzT2hwQlNuTHJvR3ZDSjQwMWlPLzMzSTFrTU9JMXZYUkxKS1JGMzkKRDRzUnVXN3kyaTE1TklNMnVVOGc0eU0yN2c1SWU3S1AzdG1UZzlGVDhDZEVyejFxRkt2TGMzSU0vdk5OMTZLdQpBb2tueEZNazVDNUdtNDlnR09BWWJUMXEyYXY3UVc2QUNPVnA0TFhSeG55emZGK1plZHZid3RtSDZJMEx2MGRmClloQ3QxUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0h3WUQKVlIwakJCZ3dGb0FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQURGOStaNG1IWlBrNmhLNlpLUk5NakF0N0ZmdVozV1V3emxJSlhyYlJ4MUtGCjZIaFZpbThHNllnd1YzUW1jSVdFbTZISzE1a2dWbWpKaitVazZZVVliYXdYRGNvWXRrNEQvVkkzWHU0cE4zeU4KeXQ3anhNeDVuMDJlRStzVFJqbU9MeEZxbG5FMlB1S09tallkTHJaTThlaDI2OEVZUVNSTlczN3VTZUVLNVFhUgp5TVZFcXRqZGVSZEJHTkRZZkVTLzV4WnZubjBZT0VBQTFHVHFSbEJXdzdnOC9vZWttY0VqV1FmNUduVks4bHUzClBVOUYrQW5Gam56MzI4aHE5V1AzWUZUVFAwaW9vTTBqOGJTTDI4ZklPZ0p1UURQMFBGN0ErbzlveExHN2ZXTUYKR3RzWElhajdWOHFSRmhCNDgvc245eThuR1libnQ3QzhFNjc3cjl1b1F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-v1-daemonset
  failurePolicy: Fail
  name: mdaemonset.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daemonsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lKQU8xM2hZZnh2K1NDTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014SVRBZkJnTlYKQkFNTUdHUnBZM1JoZEc5eUxtdDFZbVV0YzNsemRHVnRMbk4yWXpBZ0Z3MHlNekE1TURVd05qTXpOVEJhR0E4eQpNRFV4TURFeU1UQTJNek0xTUZvd0l6RWhNQjhHQTFVRUF3d1laR2xqZEdGMGIzSXVhM1ZpWlMxemVYTjBaVzB1CmMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVZc2tVbnRnTDJXaFdmTkEKOXBCY1NRVHJwMU9EL0dTRXVKWmRpdFdTelNuKyt6TmJCa3JhT3pUblR2Tk9RNGkrSmQ0eFpHeHpEeWg1M1FrNAp4UEFNQUxwSnVSa1h1M0x0cmRNT2QrRjVMNDRlMkMxVnZUR043dnl4QUV6ZTk4YUN0NzBrOWdKZXpGM1BZTWwzCklSb1BiaVVqekQxcDc4UlRYZ2FibkRNTzgzT2hwQlNuTHJvR3ZDSjQwMWlPLzMzSTFrTU9JMXZYUkxKS1JGMzkKRDRzUnVXN3kyaTE1TklNMnVVOGc0eU0yN2c1SWU3S1AzdG1UZzlGVDhDZEVyejFxRkt2TGMzSU0vdk5OMTZLdQpBb2tueEZNazVDNUdtNDlnR09BWWJUMXEyYXY3UVc2QUNPVnA0TFhSeG55emZGK1plZHZid3RtSDZJMEx2MGRmClloQ3QxUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0h3WUQKVlIwakJCZ3dGb0FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQURGOStaNG1IWlBrNmhLNlpLUk5NakF0N0ZmdVozV1V3emxJSlhyYlJ4MUtGCjZIaFZpbThHNllnd1YzUW1jSVdFbTZISzE1a2dWbWpKaitVazZZVVliYXdYRGNvWXRrNEQvVkkzWHU0cE4zeU4KeXQ3anhNeDVuMDJlRStzVFJqbU9MeEZxbG5FMlB1S09tallkTHJaTThlaDI2OEVZUVNSTlczN3VTZUVLNVFhUgp5TVZFcXRqZGVSZEJHTkRZZkVTLzV4WnZubjBZT0VBQTFHVHFSbEJXdzdnOC9vZWttY0VqV1FmNUduVks4bHUzClBVOUYrQW5Gam56MzI4aHE5V1AzWUZUVFAwaW9vTTBqOGJTTDI4ZklPZ0p1UURQMFBGN0ErbzlveExHN2ZXTUYKR3RzWElhajdWOHFSRmhCNDgvc245eThuR1libnQ3QzhFNjc3cjl1b1F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-v1-deployment
  failurePolicy: Fail
  name: mdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lKQU8xM2hZZnh2K1NDTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014SVRBZkJnTlYKQkFNTUdHUnBZM1JoZEc5eUxtdDFZbVV0YzNsemRHVnRMbk4yWXpBZ0Z3MHlNekE1TURVd05qTXpOVEJhR0E4eQpNRFV4TURFeU1UQTJNek0xTUZvd0l6RWhNQjhHQTFVRUF3d1laR2xqZEdGMGIzSXVhM1ZpWlMxemVYTjBaVzB1CmMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVZc2tVbnRnTDJXaFdmTkEKOXBCY1NRVHJwMU9EL0dTRXVKWmRpdFdTelNuKyt6TmJCa3JhT3pUblR2Tk9RNGkrSmQ0eFpHeHpEeWg1M1FrNAp4UEFNQUxwSnVSa1h1M0x0cmRNT2QrRjVMNDRlMkMxVnZUR043dnl4QUV6ZTk4YUN0NzBrOWdKZXpGM1BZTWwzCklSb1BiaVVqekQxcDc4UlRYZ2FibkRNTzgzT2hwQlNuTHJvR3ZDSjQwMWlPLzMzSTFrTU9JMXZYUkxKS1JGMzkKRDRzUnVXN3kyaTE1TklNMnVVOGc0eU0yN2c1SWU3S1AzdG1UZzlGVDhDZEVyejFxRkt2TGMzSU0vdk5OMTZLdQpBb2tueEZNazVDNUdtNDlnR09BWWJUMXEyYXY3UVc2QUNPVnA0TFhSeG55emZGK1plZHZid3RtSDZJMEx2MGRmClloQ3QxUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0h3WUQKVlIwakJCZ3dGb0FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQURGOStaNG1IWlBrNmhLNlpLUk5NakF0N0ZmdVozV1V3emxJSlhyYlJ4MUtGCjZIaFZpbThHNllnd1YzUW1jSVdFbTZISzE1a2dWbWpKaitVazZZVVliYXdYRGNvWXRrNEQvVkkzWHU0cE4zeU4KeXQ3anhNeDVuMDJlRStzVFJqbU9MeEZxbG5FMlB1S09tallkTHJaTThlaDI2OEVZUVNSTlczN3VTZUVLNVFhUgp5TVZFcXRqZGVSZEJHTkRZZkVTLzV4WnZubjBZT0VBQTFHVHFSbEJXdzdnOC9vZWttY0VqV1FmNUduVks4bHUzClBVOUYrQW5Gam56MzI4aHE5V1AzWUZUVFAwaW9vTTBqOGJTTDI4ZklPZ0p1UURQMFBGN0ErbzlveExHN2ZXTUYKR3RzWElhajdWOHFSRmhCNDgvc245eThuR1libnQ3QzhFNjc3cjl1b1F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-v1-statefulset
  failurePolicy: Fail
  name: mstatefulset.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - statefulsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lKQU8xM2hZZnh2K1NDTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014SVRBZkJnTlYKQkFNTUdHUnBZM1JoZEc5eUxtdDFZbVV0YzNsemRHVnRMbk4yWXpBZ0Z3MHlNekE1TURVd05qTXpOVEJhR0E4eQpNRFV4TURFeU1UQTJNek0xTUZvd0l6RWhNQjhHQTFVRUF3d1laR2xqZEdGMGIzSXVhM1ZpWlMxemVYTjBaVzB1CmMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVZc2tVbnRnTDJXaFdmTkEKOXBCY1NRVHJwMU9EL0dTRXVKWmRpdFdTelNuKyt6TmJCa3JhT3pUblR2Tk9RNGkrSmQ0eFpHeHpEeWg1M1FrNAp4UEFNQUxwSnVSa1h1M0x0cmRNT2QrRjVMNDRlMkMxVnZUR043dnl4QUV6ZTk4YUN0NzBrOWdKZXpGM1BZTWwzCklSb1BiaVVqekQxcDc4UlRYZ2FibkRNTzgzT2hwQlNuTHJvR3ZDSjQwMWlPLzMzSTFrTU9JMXZYUkxKS1JGMzkKRDRzUnVXN3kyaTE1TklNMnVVOGc0eU0yN2c1SWU3S1AzdG1UZzlGVDhDZEVyejFxRkt2TGMzSU0vdk5OMTZLdQpBb2tueEZNazVDNUdtNDlnR09BWWJUMXEyYXY3UVc2QUNPVnA0TFhSeG55emZGK1plZHZid3RtSDZJMEx2MGRmClloQ3QxUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0h3WUQKVlIwakJCZ3dGb0FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQURGOStaNG1IWlBrNmhLNlpLUk5NakF0N0ZmdVozV1V3emxJSlhyYlJ4MUtGCjZIaFZpbThHNllnd1YzUW1jSVdFbTZISzE1a2dWbWpKaitVazZZVVliYXdYRGNvWXRrNEQvVkkzWHU0cE4zeU4KeXQ3anhNeDVuMDJlRStzVFJqbU9MeEZxbG5FMlB1S09tallkTHJaTThlaDI2OEVZUVNSTlczN3VTZUVLNVFhUgp5TVZFcXRqZGVSZEJHTkRZZkVTLzV4WnZubjBZT0VBQTFHVHFSbEJXdzdnOC9vZWttY0VqV1FmNUduVks4bHUzClBVOUYrQW5Gam56MzI4aHE5V1AzWUZUVFAwaW9vTTBqOGJTTDI4ZklPZ0p1UURQMFBGN0ErbzlveExHN2ZXTUYKR3RzWElhajdWOHFSRmhCNDgvc245eThuR1libnQ3QzhFNjc3cjl1b1F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-v1-daemonset
  failurePolicy: Fail
  name: vdaemonset.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daemonsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lKQU8xM2hZZnh2K1NDTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014SVRBZkJnTlYKQkFNTUdHUnBZM1JoZEc5eUxtdDFZbVV0YzNsemRHVnRMbk4yWXpBZ0Z3MHlNekE1TURVd05qTXpOVEJhR0E4eQpNRFV4TURFeU1UQTJNek0xTUZvd0l6RWhNQjhHQTFVRUF3d1laR2xqZEdGMGIzSXVhM1ZpWlMxemVYTjBaVzB1CmMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVZc2tVbnRnTDJXaFdmTkEKOXBCY1NRVHJwMU9EL0dTRXVKWmRpdFdTelNuKyt6TmJCa3JhT3pUblR2Tk9RNGkrSmQ0eFpHeHpEeWg1M1FrNAp4UEFNQUxwSnVSa1h1M0x0cmRNT2QrRjVMNDRlMkMxVnZUR043dnl4QUV6ZTk4YUN0NzBrOWdKZXpGM1BZTWwzCklSb1BiaVVqekQxcDc4UlRYZ2FibkRNTzgzT2hwQlNuTHJvR3ZDSjQwMWlPLzMzSTFrTU9JMXZYUkxKS1JGMzkKRDRzUnVXN3kyaTE1TklNMnVVOGc0eU0yN2c1SWU3S1AzdG1UZzlGVDhDZEVyejFxRkt2TGMzSU0vdk5OMTZLdQpBb2tueEZNazVDNUdtNDlnR09BWWJUMXEyYXY3UVc2QUNPVnA0TFhSeG55emZGK1plZHZid3RtSDZJMEx2MGRmClloQ3QxUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0h3WUQKVlIwakJCZ3dGb0FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQURGOStaNG1IWlBrNmhLNlpLUk5NakF0N0ZmdVozV1V3emxJSlhyYlJ4MUtGCjZIaFZpbThHNllnd1YzUW1jSVdFbTZISzE1a2dWbWpKaitVazZZVVliYXdYRGNvWXRrNEQvVkkzWHU0cE4zeU4KeXQ3anhNeDVuMDJlRStzVFJqbU9MeEZxbG5FMlB1S09tallkTHJaTThlaDI2OEVZUVNSTlczN3VTZUVLNVFhUgp5TVZFcXRqZGVSZEJHTkRZZkVTLzV4WnZubjBZT0VBQTFHVHFSbEJXdzdnOC9vZWttY0VqV1FmNUduVks4bHUzClBVOUYrQW5Gam56MzI4aHE5V1AzWUZUVFAwaW9vTTBqOGJTTDI4ZklPZ0p1UURQMFBGN0ErbzlveExHN2ZXTUYKR3RzWElhajdWOHFSRmhCNDgvc245eThuR1libnQ3QzhFNjc3cjl1b1F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-v1-deployment
  failurePolicy: Fail
  name: vdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lKQU8xM2hZZnh2K1NDTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ014SVRBZkJnTlYKQkFNTUdHUnBZM1JoZEc5eUxtdDFZbVV0YzNsemRHVnRMbk4yWXpBZ0Z3MHlNekE1TURVd05qTXpOVEJhR0E4eQpNRFV4TURFeU1UQTJNek0xTUZvd0l6RWhNQjhHQTFVRUF3d1laR2xqZEdGMGIzSXVhM1ZpWlMxemVYTjBaVzB1CmMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVZc2tVbnRnTDJXaFdmTkEKOXBCY1NRVHJwMU9EL0dTRXVKWmRpdFdTelNuKyt6TmJCa3JhT3pUblR2Tk9RNGkrSmQ0eFpHeHpEeWg1M1FrNAp4UEFNQUxwSnVSa1h1M0x0cmRNT2QrRjVMNDRlMkMxVnZUR043dnl4QUV6ZTk4YUN0NzBrOWdKZXpGM1BZTWwzCklSb1BiaVVqekQxcDc4UlRYZ2FibkRNTzgzT2hwQlNuTHJvR3ZDSjQwMWlPLzMzSTFrTU9JMXZYUkxKS1JGMzkKRDRzUnVXN3kyaTE1TklNMnVVOGc0eU0yN2c1SWU3S1AzdG1UZzlGVDhDZEVyejFxRkt2TGMzSU0vdk5OMTZLdQpBb2tueEZNazVDNUdtNDlnR09BWWJUMXEyYXY3UVc2QUNPVnA0TFhSeG55emZGK1plZHZid3RtSDZJMEx2MGRmClloQ3QxUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0h3WUQKVlIwakJCZ3dGb0FVMnlLMEREdVRudThVS0pXeFpaVFJQTFZzNFNjd0RBWURWUjBUQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQURGOStaNG1IWlBrNmhLNlpLUk5NakF0N0ZmdVozV1V3emxJSlhyYlJ4MUtGCjZIaFZpbThHNllnd1YzUW1jSVdFbTZISzE1a2dWbWpKaitVazZZVVliYXdYRGNvWXRrNEQvVkkzWHU0cE4zeU4KeXQ3anhNeDVuMDJlRStzVFJqbU9MeEZxbG5FMlB1S09tallkTHJaTThlaDI2OEVZUVNSTlczN3VTZUVLNVFhUgp5TVZFcXRqZGVSZEJHTkRZZkVTLzV4WnZubjBZT0VBQTFHVHFSbEJXdzdnOC9vZWttY0VqV1FmNUduVks4bHUzClBVOUYrQW5Gam56MzI4aHE5V1AzWUZUVFAwaW9vTTBqOGJTTDI4ZklPZ0p1UURQMFBGN0ErbzlveExHN2ZXTUYKR3RzWElhajdWOHFSRmhCNDgvc245eThuR1libnQ3QzhFNjc3cjl1b1F3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-v1-statefulset
  failurePolicy: Fail
  name: vstatefulset.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - statefulsets
  sideEffects: None
