---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: dictator.wellcloud.welljoint.com
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: dictator
      path: /mutate-apps-v1-deployment
  failurePolicy: Fail
  name: mdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: dictator.wellcloud.welljoint.com
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: dictator
      path: /validate-apps-v1-deployment
  failurePolicy: Fail
  name: vdeployment.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
  sideEffects: None
