apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dictator
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dictator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dictator
subjects:
  - kind: ServiceAccount
    name: dictator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dictator
